/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StationAccessibilityRouteImport } from './routes/station-accessibility'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SavedTripsRouteImport } from './routes/saved-trips'
import { Route as RouteOverviewRouteImport } from './routes/route-overview'
import { Route as RouteDetailsRouteImport } from './routes/route-details'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingDesktopRouteImport } from './routes/onboarding-desktop'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LiveNavigationRouteImport } from './routes/live-navigation'
import { Route as AlternativeRoutesRouteImport } from './routes/alternative-routes'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as IndexRouteImport } from './routes/index'

const StationAccessibilityRoute = StationAccessibilityRouteImport.update({
  id: '/station-accessibility',
  path: '/station-accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedTripsRoute = SavedTripsRouteImport.update({
  id: '/saved-trips',
  path: '/saved-trips',
  getParentRoute: () => rootRouteImport,
} as any)
const RouteOverviewRoute = RouteOverviewRouteImport.update({
  id: '/route-overview',
  path: '/route-overview',
  getParentRoute: () => rootRouteImport,
} as any)
const RouteDetailsRoute = RouteDetailsRouteImport.update({
  id: '/route-details',
  path: '/route-details',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingDesktopRoute = OnboardingDesktopRouteImport.update({
  id: '/onboarding-desktop',
  path: '/onboarding-desktop',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveNavigationRoute = LiveNavigationRouteImport.update({
  id: '/live-navigation',
  path: '/live-navigation',
  getParentRoute: () => rootRouteImport,
} as any)
const AlternativeRoutesRoute = AlternativeRoutesRouteImport.update({
  id: '/alternative-routes',
  path: '/alternative-routes',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/alternative-routes': typeof AlternativeRoutesRoute
  '/live-navigation': typeof LiveNavigationRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/onboarding-desktop': typeof OnboardingDesktopRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/route-details': typeof RouteDetailsRoute
  '/route-overview': typeof RouteOverviewRoute
  '/saved-trips': typeof SavedTripsRoute
  '/settings': typeof SettingsRoute
  '/station-accessibility': typeof StationAccessibilityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/alternative-routes': typeof AlternativeRoutesRoute
  '/live-navigation': typeof LiveNavigationRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/onboarding-desktop': typeof OnboardingDesktopRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/route-details': typeof RouteDetailsRoute
  '/route-overview': typeof RouteOverviewRoute
  '/saved-trips': typeof SavedTripsRoute
  '/settings': typeof SettingsRoute
  '/station-accessibility': typeof StationAccessibilityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/alternative-routes': typeof AlternativeRoutesRoute
  '/live-navigation': typeof LiveNavigationRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/onboarding-desktop': typeof OnboardingDesktopRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/route-details': typeof RouteDetailsRoute
  '/route-overview': typeof RouteOverviewRoute
  '/saved-trips': typeof SavedTripsRoute
  '/settings': typeof SettingsRoute
  '/station-accessibility': typeof StationAccessibilityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/alternative-routes'
    | '/live-navigation'
    | '/login'
    | '/onboarding'
    | '/onboarding-desktop'
    | '/profile'
    | '/register'
    | '/route-details'
    | '/route-overview'
    | '/saved-trips'
    | '/settings'
    | '/station-accessibility'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/alternative-routes'
    | '/live-navigation'
    | '/login'
    | '/onboarding'
    | '/onboarding-desktop'
    | '/profile'
    | '/register'
    | '/route-details'
    | '/route-overview'
    | '/saved-trips'
    | '/settings'
    | '/station-accessibility'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/alternative-routes'
    | '/live-navigation'
    | '/login'
    | '/onboarding'
    | '/onboarding-desktop'
    | '/profile'
    | '/register'
    | '/route-details'
    | '/route-overview'
    | '/saved-trips'
    | '/settings'
    | '/station-accessibility'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  AlternativeRoutesRoute: typeof AlternativeRoutesRoute
  LiveNavigationRoute: typeof LiveNavigationRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  OnboardingDesktopRoute: typeof OnboardingDesktopRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  RouteDetailsRoute: typeof RouteDetailsRoute
  RouteOverviewRoute: typeof RouteOverviewRoute
  SavedTripsRoute: typeof SavedTripsRoute
  SettingsRoute: typeof SettingsRoute
  StationAccessibilityRoute: typeof StationAccessibilityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/station-accessibility': {
      id: '/station-accessibility'
      path: '/station-accessibility'
      fullPath: '/station-accessibility'
      preLoaderRoute: typeof StationAccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved-trips': {
      id: '/saved-trips'
      path: '/saved-trips'
      fullPath: '/saved-trips'
      preLoaderRoute: typeof SavedTripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/route-overview': {
      id: '/route-overview'
      path: '/route-overview'
      fullPath: '/route-overview'
      preLoaderRoute: typeof RouteOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/route-details': {
      id: '/route-details'
      path: '/route-details'
      fullPath: '/route-details'
      preLoaderRoute: typeof RouteDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding-desktop': {
      id: '/onboarding-desktop'
      path: '/onboarding-desktop'
      fullPath: '/onboarding-desktop'
      preLoaderRoute: typeof OnboardingDesktopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-navigation': {
      id: '/live-navigation'
      path: '/live-navigation'
      fullPath: '/live-navigation'
      preLoaderRoute: typeof LiveNavigationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alternative-routes': {
      id: '/alternative-routes'
      path: '/alternative-routes'
      fullPath: '/alternative-routes'
      preLoaderRoute: typeof AlternativeRoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  AlternativeRoutesRoute: AlternativeRoutesRoute,
  LiveNavigationRoute: LiveNavigationRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  OnboardingDesktopRoute: OnboardingDesktopRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  RouteDetailsRoute: RouteDetailsRoute,
  RouteOverviewRoute: RouteOverviewRoute,
  SavedTripsRoute: SavedTripsRoute,
  SettingsRoute: SettingsRoute,
  StationAccessibilityRoute: StationAccessibilityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
