import type { FilterOption, TrainResult } from './types';

export const FILTER_OPTIONS: FilterOption[] = [
  { key: 'all', label: 'Alle' },
  { key: 'fastest', label: 'Schnellste' },
  { key: 'fewest-transfers', label: 'Wenigste Umstiege' },
  { key: 'accessible', label: 'Barrierefrei' },
  { key: 'step-free', label: 'Nur Stufenfrei' },
  { key: 'ice-only', label: 'Nur ICE' },
];

export const MOCK_RESULTS: TrainResult[] = [
  {
    id: 'ice-789',
    trainType: 'ICE 789',
    departureTime: '08:32',
    arrivalTime: '10:14',
    duration: '1 Std. 42 Min.',
    transfers: 0,
    status: 'ontime',
    isAccessible: true,
    accessibilityNote: 'Vollständig barrierefrei',
    crowdLevel: 'low',
    price: '€ 44,90',
    platform: 'Gleis 7',
  },
  {
    id: 'ice-1605',
    trainType: 'ICE 1605',
    departureTime: '09:02',
    arrivalTime: '11:05',
    duration: '2 Std. 3 Min.',
    transfers: 1,
    status: 'delayed',
    delayMinutes: 12,
    isAccessible: true,
    accessibilityNote: 'Barrierefrei mit Einschränkung',
    crowdLevel: 'moderate',
    price: '€ 32,50',
    platform: 'Gleis 4',
  },
  {
    id: 'ec-173',
    trainType: 'EC 173',
    departureTime: '09:35',
    arrivalTime: '11:22',
    duration: '1 Std. 47 Min.',
    transfers: 0,
    status: 'cancelled',
    isAccessible: false,
    accessibilityNote: 'Aufzug defekt — Alternative verfügbar',
    crowdLevel: 'high',
    price: '€ 56,00',
    platform: 'Gleis 12',
  },
  {
    id: 'ice-599',
    trainType: 'ICE 599',
    departureTime: '10:05',
    arrivalTime: '11:52',
    duration: '1 Std. 47 Min.',
    transfers: 0,
    status: 'ontime',
    isAccessible: true,
    accessibilityNote: 'Vollständig barrierefrei',
    crowdLevel: 'low',
    price: '€ 49,90',
    platform: 'Gleis 3',
  },
];
